name: Create new tag when a pull request is merged into the main branch workflow
# on:
#   pull_request:
#     types:
#       - closed
#     branches:
#       - main
# jobs:
#   print:
#     runs-on: ubuntu-latest
#     steps:
#       - name: print
#         run: |
#           echo '${{ toJSON(github) }}'

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo "The PR was merged!"
