name: Create new tag when a pull request is merged into the main branch workflow
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  print:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: |
          TAG=$(git describe --tag --abbrev=0)
          echo '${{ toJSON(github.event) }}'
          echo ${TAG}
