name: New tag workflow
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Google Cloud Authentication with service account
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Print
        run: |
          echo '${{ toJSON(github) }}'
