name: New tag workflow
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Google Cloud Authentication with service account
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Print
        run: |
          echo '${{ toJSON(github) }}'

      - name: Config Docker by Google Cloud
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

      - name: Set Docker build and Artifact Registry variables
        run: |
          echo "ARTIFACT_IMAGE_PATH=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/${{secrets.GCP_ARTIFACT_REPO}}/en-vocab-server" >> $GITHUB_ENV
          echo "ARTIFACT_IMAGE_TAG"=${{ github.ref_name }} >> $GITHUB_ENV
          # echo "PAT=${{secrets.PAT}}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          DOCKER_BUILD_TAG=$ARTIFACT_IMAGE_PATH:$ARTIFACT_IMAGE_TAG
          docker build --secret id=github_pat,env=GITHUB_PAT -t $DOCKER_BUILD_TAG .
        env:
          GITHUB_PAT: ${{ secrets.PAT }}

      - name: Push Docker image to Artifact Registry
        run: |
          DOCKER_BUILD_TAG=$ARTIFACT_IMAGE_PATH:$ARTIFACT_IMAGE_TAG
          docker push $DOCKER_BUILD_TAG
