name: Trigger telegram for pull requests are ready for review
on:
  pull_request:
    types:
      - review_requested
      - labeled
jobs:
  print-info:
    name: Print the information about this trigger
    runs-on: ubuntu-latest
    steps:
      - name: Print context
        run: |
          SENDER=${{toJSON(github.event.pull_request.head.user)}}
          RECEIVER=${{toJSON(github.event.pull_request.requested_reviewers)}}
          echo "$SENDER"
