name: Trigger telegram for pull requests are ready for review
on:
  pull_request:
    types:
      - review_requested
      - labeled
jobs:
  print-info:
    name: Print the information about this trigger
    runs-on: ubuntu-latest
    steps:
      - name: Print context
        run: |
          EVENT='${{toJSON(github.event)}}'
          SENDER='${{toJSON(github.event.pull_request.head.user)}}'
          RECEIVER='${{toJSON(github.event.pull_request.requested_reviewers)}}'
          # echo $SENDER
          # echo $RECEIVER
          echo $EVENT
      - name: Check label name to notification
        if: github.event.action == 'labeled' && github.event.label.name == 'ready for review'
        run: echo '${{toJSON(github)}}'

      - name: Send a Telegram notification
        uses: appleboy/telegram-action@master
        with:
          token: ${{ secrets.TELEGRAM_BOT_TOKEN_ID }}
          to: ${{ secrets.TELEGRAM_VIETTEL_CHAT_GROUP_ID }}
          message: |
            A new commit is ready for ${{github.event.pull_request.requested_reviewers.login}} to review !

            Repository: ${{github.repository}}

            See changes: ${{github.event.pull_request._links.html.href}}/commits/${{github.workflow_sha}}
